eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 

spring:
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: products
          uri: http://localhost:8082 /* lb://PRODUCTS */
          predicates:
            - Path=/product/**
        - id: catalog
          uri: http://localhost:8081 /* lb://PRODUCTS */
          predicates:
            - Path=/cart/**
            
